services:
  - type: web
    name: project-beetime
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_NO_WARNINGS
        value: 1
    healthCheckPath: /health
    autoDeploy: true 