services:
  - type: web
    name: project-beetime
    env: node
    buildCommand: npm install && npx prisma generate && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_NO_WARNINGS
        value: 1
    healthCheckPath: /health
    autoDeploy: true 